/** Consistent copy for disabled write actions (native `title` tooltips). */
export const PERMISSION_TOOLTIPS = {
  addUser: "You don't have permission to add users.",
  editUser: "You don't have permission to edit this user.",
  removeUser: "You don't have permission to remove this user.",
  addWorkspaceUser: "You don't have permission to add workspace users.",
  editWorkspaceUser: "You don't have permission to edit workspace roles.",
  removeWorkspaceUser: "You don't have permission to remove users from this workspace.",
  addLead: "You don't have permission to add leads.",
  bulkLeads: "You don't have permission to import leads in bulk.",
  editLead: "You don't have permission to edit leads.",
  deleteLead: "You don't have permission to delete leads.",
  moveLeadToClient: "You don't have permission to move leads to clients.",
  bulkDeleteLeads: "You don't have permission to delete selected leads.",
  leadBulkSelection: "You don't have permission to select leads for bulk actions.",
  createTemplate: "You don't have permission to create templates.",
  manageTemplate: "You don't have permission to open template management.",
  addMasterField: "You don't have permission to add master fields.",
  bulkMasterFields: "You don't have permission to import master fields in bulk.",
  editMasterField: "You don't have permission to edit master fields.",
  deleteMasterField: "You don't have permission to delete master fields.",
  deleteMasterFieldsBulk: "You don't have permission to delete master fields.",
  masterFieldBulkSelection: "You don't have permission to select fields for bulk delete.",
  removeYourselfWorkspace: "You cannot remove yourself from this workspace.",
  editWorkspaceFullAccess: "You don't have permission to change roles for full-access users.",
  removeWorkspaceFullAccess: "You don't have permission to remove full-access users from this workspace.",
  editOrgOwner: "Organization owners cannot be edited here.",
  removeOrgMemberProtected: "This member cannot be removed due to role protection rules.",
  addClient: "You don't have permission to create clients.",
  editClient: "You don't have permission to edit clients.",
  manageClient: "You don't have permission to open this client workspace.",
} as const;
