import Avatar, { type AvatarProps } from "./Avatar";
import Tooltip from "./Tooltip";
import type { FileRef } from "../../types/extraction.types";
import { timeAgo } from "../../utils/date";
import { getUserDisplayName, normalizeUserForAvatar, type UserInfo } from "../../utils/userUtils";
import { cn } from "../../utils/cn";

/** Verb phrase in tooltip, e.g. "uploaded by" → "Uploaded by {name} 2 weeks ago". */
export type UserActionVerb =
  | "uploaded by"
  | "extracted by"
  | "edited by"
  | "reviewed by"
  | "approved by"
  | "generated by"
  | "action by";

export type UserAction = {
  user: UserInfo | Record<string, unknown> | null | undefined;
  action: UserActionVerb | string;
  timestamp?: string | Date | null;
};

const AUDIT_ACTION_LABELS: Record<string, UserActionVerb | string> = {
  field_extracted: "extracted by",
  field_edited: "edited by",
  field_reviewed: "reviewed by",
  field_approved: "approved by",
};

export function auditActionLabel(action: string): UserActionVerb | string {
  return AUDIT_ACTION_LABELS[action] ?? "action by";
}

export function formatUserActionTooltip(
  action: string,
  user: UserInfo | Record<string, unknown> | null | undefined,
  timestamp?: string | Date | null
): string {
  const userName = getUserDisplayName(normalizeUserForAvatar(user)) || "Unknown";
  const verb = action.trim();
  const label = verb ? verb.charAt(0).toUpperCase() + verb.slice(1) : "Action by";
  const ago = timestamp ? ` ${timeAgo(timestamp)}` : "";
  return `${label} ${userName}${ago}`;
}

export function isResolvableUser(
  user: UserInfo | Record<string, unknown> | string | null | undefined
): user is UserInfo | Record<string, unknown> {
  return Boolean(user) && typeof user !== "string";
}

export type AuditTrailEntryLike = {
  _id?: string;
  user_id?: {
    _id?: string;
    fullName?: string;
    email?: string;
    username?: string;
  } | null;
  user_name?: string;
  user_email?: string;
  action: string;
  timestamp: string;
};

export function auditTrailToUserActions(entries: AuditTrailEntryLike[]): UserAction[] {
  const actions: UserAction[] = entries
    .filter((entry) => entry.user_id || entry.user_name || entry.user_email)
    .map((entry) => {
      const user =
        entry.user_id ||
        ({
          _id: entry._id,
          fullName: entry.user_name,
          email: entry.user_email,
        } as Record<string, unknown>);

      return {
        user,
        action: auditActionLabel(entry.action),
        timestamp: entry.timestamp,
      };
    });

  return actions.reduce<UserAction[]>((acc, action) => {
    const userKey =
      (action.user as UserInfo)?._id ||
      (action.user as UserInfo)?.email ||
      (action.user as Record<string, unknown>)?.email ||
      "unknown";
    const key = `${userKey}_${action.action}`;
    if (!acc.find((a) => `${(a.user as UserInfo)?._id || (a.user as UserInfo)?.email}_${a.action}` === key)) {
      acc.push(action);
    }
    return acc;
  }, []);
}

export type UserActionAvatarProps = {
  user: AvatarProps["user"] | Record<string, unknown> | string | null | undefined;
  action: UserActionVerb | string;
  timestamp?: string | Date | null;
  size?: AvatarProps["size"];
  className?: string;
  placement?: "top" | "bottom" | "left" | "right";
  unknownLabel?: string;
};

/** Avatar with portal tooltip: "{Action} by {name} {time ago}". */
export default function UserActionAvatar({
  user,
  action,
  timestamp,
  size = "xs",
  className,
  placement = "top",
  unknownLabel = "Unknown",
}: UserActionAvatarProps) {
  if (!isResolvableUser(user)) {
    return <span className={cn("text-card-text text-xs", className)}>{unknownLabel}</span>;
  }

  const normalized = normalizeUserForAvatar(user);
  const tooltip = formatUserActionTooltip(action, normalized, timestamp);

  return (
    <Tooltip content={tooltip} placement={placement}>
      <Avatar user={normalized} size={size} className={className} />
    </Tooltip>
  );
}

export function formatDocumentCreatedLabel(
  uploadedAt?: string | Date | null,
  uploadDate?: string | Date | null,
  createdAt?: string | Date | null
): string {
  const raw = uploadedAt || uploadDate || createdAt;
  return raw ? new Date(raw).toLocaleString() : "Unknown";
}

export type DocumentUploaderMetaProps = {
  uploadedBy?: FileRef["uploaded_by"];
  tooltipUploadedAt?: string | Date | null;
  uploadDate?: string | Date | null;
  createdAt?: string | Date | null;
  size?: AvatarProps["size"];
};

function verbPastTense(verb: UserActionVerb | string): string {
  if (verb === "uploaded by") return "Uploaded";
  if (verb === "generated by") return "Generated";
  const trimmed = verb.trim();
  if (!trimmed) return "Action";
  return trimmed.charAt(0).toUpperCase() + trimmed.slice(1);
}

export type DocumentActorMetaProps = {
  user?: FileRef["uploaded_by"];
  verb?: UserActionVerb;
  timestamp?: string | Date | null;
  size?: AvatarProps["size"];
};

/** Document card header: actor avatar + action time ago. */
export function DocumentActorMeta({
  user,
  verb = "uploaded by",
  timestamp,
  size = "xs",
}: DocumentActorMetaProps) {
  const agoLabel = timestamp ? timeAgo(timestamp) : null;

  return (
    <div className="mt-1 flex min-w-0 items-center gap-2 text-xs text-card-text">
      <UserActionAvatar
        user={isResolvableUser(user) ? user : null}
        action={verb}
        timestamp={timestamp}
        size={size}
      />
      {agoLabel ? (
        <span className="min-w-0 truncate">
          {verbPastTense(verb)} {agoLabel}
        </span>
      ) : null}
    </div>
  );
}

/** Document card header: uploader avatar + uploaded time ago. */
export function DocumentUploaderMeta({
  uploadedBy,
  tooltipUploadedAt,
  uploadDate,
  createdAt,
  size = "xs",
}: DocumentUploaderMetaProps) {
  return (
    <DocumentActorMeta
      user={uploadedBy}
      verb="uploaded by"
      timestamp={tooltipUploadedAt || uploadDate || createdAt}
      size={size}
    />
  );
}
